name = "rust-sr"
main = "dist/worker.js"
compatibility_date = "2024-10-21"

[build]
command = "npm run build"

# Environment variables (use wrangler secret put YOUTUBE_API_KEY)
# [vars]
# YOUTUBE_API_KEY = "your_youtube_api_key_here"
